graph TD;

AotDS --> aotds-battle
AotDS --> aotds-server
AotDS --> aotds-app
AotDS -- for this diagram --> mermaid 

aotds-battle -- js package management --> pnpm
aotds-app -- js package management --> pnpm
aotds-server -- js package management --> pnpm

aotds-battle --> babel
aotds-app --> babel
aotds-server --> babel 

aotds-app --> webstack

aotds-battle -->|task runner| gotask
aotds-app -->|task runner| gotask
aotds-server -->|task runner| gotask 

aotds-server -->|auth| jwt 

aotds-app --> react 
aotds-app --> redux

aotds-battle -->|game state| redux 

aotds-battle --> json-schema 
json-schema -->|purty viewing| docson 

aotds-server --> objection 
objection -->|db migrations| knex 
objection -->|fast, easy, cheap| SQLite 

aotds-server --> koa 
aotds-server -->|api definition| swagger

